services:
  - type: web
    name: au-thumbnail-changer-bot
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: API_TOKEN
        sync: false
      - key: MONGO_URL
        sync: false
      - key: OWNER_ID
        sync: false
      - key: CHANNEL_URL
        sync: false
      - key: DEV_URL
        sync: false

#Don't Remove Credits 
#Supports Group @AU_Bot_Discussion 
#Telegram Channel @Anime_UpdatesAU
#Developer @Mr_Mohammed_29
